version: '3.8'

services:
  backend:
    build:
      context: ./django
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./angular
    container_name: angular_frontend
    ports:
      - "4200:4200"  # Mapping Angular's port 4200 for development
    volumes:
      - ./angular:/app
      - /app/node_modules  
    environment:
      - CHOKIDAR_USEPOLLING=true  
    depends_on:
      - backend
    command: npm run start -- --host 0.0.0.0  

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
